#!/usr/bin/env python3
"""Remove what outlived its work — only what loses nothing, unless told otherwise.

WHY. The survey (collectors/scan_git_hygiene.py, collectors/scan_machine.py)
says what is there; this acts on it. On 2026-09-27 the same afternoon's work was
done by hand: 418 branches and 68 worktrees removed, build output of idle
projects deleted, uncommitted edits archived first. The rules that made that
safe are the rules here.

TWO TIERS (config/cleanup.json):
  auto    loses nothing. A merged branch's commits are on the default branch; a
          pushed branch's are on its remote; a clean worktree's branch stays when
          the worktree goes; a missing worktree is only a stale record; ignored
          build output is regenerated by the next build. Runs on every tick when
          `features.auto_cleanup` is true.
  manual  the only copy of somebody's work: a branch with unique commits, a
          worktree with uncommitted edits. `--apply --include manual` archives it
          first — a thin git bundle, a patch plus a tarball of untracked files —
          and never runs on a tick.

EVERY TARGET IS RE-CHECKED at the moment it is acted on, because the survey may be
half an hour old and an agent may have started work since: a branch must still
be merged/pushed, a worktree still clean and nobody's working directory.

Every action is one line in store/logs/cleanup.jsonl with what is needed to undo
it (a branch's sha, an archive path).

    cleanup.py                           plan only; writes store/raw/cleanup-plan.json
    cleanup.py --auto                    apply the auto tier if features.auto_cleanup
    cleanup.py --apply [--include manual] apply now (operator or an agent on their word)
"""
from __future__ import annotations

import fnmatch
import json
import os
import pathlib
import shutil
import subprocess
import sys
import tarfile
import time
from datetime import datetime, timezone

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
sys.path.insert(0, str(ROOT / "collectors"))
import configuration  # noqa: E402
import paths  # noqa: E402

AUTO_CLASSES = ("branch-merged", "branch-pushed", "worktree-missing", "worktree-clean", "build-artifacts")
MANUAL_CLASSES = ("branch-unique", "worktree-dirty")


def now() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")


def load_config() -> dict:
    for f in (paths.config_file("cleanup.json"), ROOT / "defaults" / "cleanup.json"):
        try:
            return json.loads(f.read_text(encoding="utf-8"))
        except (OSError, ValueError):
            continue
    return {}


def git(repo: str, *args: str, timeout: int = 120) -> subprocess.CompletedProcess:
    return subprocess.run(["git", "-C", repo, *args], capture_output=True, text=True, timeout=timeout,
                          env={**os.environ, "LC_ALL": "C"})


def protected(name: str, cfg: dict) -> bool:
    return any(fnmatch.fnmatch(name, pat) for pat in cfg.get("protect") or [])


# --- the plan -----------------------------------------------------------------

def plan_git(hygiene: dict, cfg: dict) -> list[dict]:
    auto, manual = cfg.get("auto") or {}, cfg.get("manual") or {}
    out = []
    for c in hygiene.get("checkouts") or []:
        repo, default = c["path"], c["default_branch"]
        base = {"repository": c["repository"], "repo": repo, "default_branch": default}
        for b in c.get("branches") or []:
            if protected(b["name"], cfg):
                continue
            idle = b.get("idle_days") or 0
            if b["class"] in ("merged", "patch-merged") and idle >= auto.get("merged_branch_idle_days", 7):
                out.append({**base, "class": "branch-merged", "tier": "auto", "target": b["name"],
                            "why": f"{b['class']}, idle {idle} days"})
            elif b["class"] == "pushed" and idle >= auto.get("pushed_branch_idle_days", 30):
                out.append({**base, "class": "branch-pushed", "tier": "auto", "target": b["name"],
                            "why": f"identical to {b.get('upstream')}, idle {idle} days"})
            elif b["class"] == "unique" and idle >= manual.get("unique_branch_idle_days", 14):
                out.append({**base, "class": "branch-unique", "tier": "manual", "target": b["name"],
                            "why": f"{b['ahead']} commit(s) found nowhere else, idle {idle} days"})
        for w in c.get("worktrees") or []:
            if w.get("locked") or w.get("busy"):
                continue
            idle = w.get("idle_days") or 0
            if w["state"] == "missing":
                out.append({**base, "class": "worktree-missing", "tier": "auto", "target": w["path"],
                            "why": "its directory no longer exists"})
            elif w["state"] == "clean" and idle >= auto.get("clean_worktree_idle_days", 7):
                out.append({**base, "class": "worktree-clean", "tier": "auto", "target": w["path"],
                            "branch": w.get("branch"), "why": f"no uncommitted change, idle {idle} days"})
            elif w["state"] == "dirty" and idle >= manual.get("dirty_worktree_idle_days", 7):
                out.append({**base, "class": "worktree-dirty", "tier": "manual", "target": w["path"],
                            "branch": w.get("branch"), "why": f"{w.get('dirty_files')} uncommitted file(s), idle {idle} days"})
    return out


def idle_projects(days: int) -> list[dict]:
    try:
        doc = json.loads((paths.REGISTRY / "projects.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return []
    today = datetime.now(timezone.utc).date()
    out = []
    for p in doc.get("projects") or []:
        stamps = [p.get(k) for k in ("last_activity_on", "last_session_on") if p.get(k)]
        if not stamps or not p.get("local_folders"):
            continue
        try:
            age = (today - datetime.fromisoformat(max(stamps)).date()).days
        except ValueError:
            continue
        if age >= days:
            out.append({"id": p["id"], "folders": p["local_folders"], "idle_days": age})
    return out


def plan_artifacts(cfg: dict, busy: set[str]) -> list[dict]:
    names = set(cfg.get("artifact_dirs") or [])
    days = (cfg.get("auto") or {}).get("build_artifacts_project_idle_days", 30)
    out = []
    for p in idle_projects(days):
        for folder in p["folders"]:
            root = os.path.join(str(paths.DATA), folder)
            if not os.path.isdir(root) or os.path.islink(root):
                continue
            for dirpath, dirnames, _ in os.walk(root):
                depth = dirpath[len(root):].count(os.sep)
                keep = []
                for d in dirnames:
                    full = os.path.join(dirpath, d)
                    if d == ".git" or os.path.islink(full):
                        continue
                    if d in names:
                        ignored = git(dirpath, "check-ignore", "-q", full).returncode == 0
                        in_repo = git(dirpath, "rev-parse", "--git-dir").returncode == 0
                        if (ignored or not in_repo) and not any(b == full or b.startswith(full + "/") for b in busy):
                            out.append({"class": "build-artifacts", "tier": "auto", "target": full,
                                        "project": p["id"], "why": f"{'git-ignored' if in_repo else 'outside git'} "
                                                                   f"build output; project idle {p['idle_days']} days"})
                        continue
                    if depth < 5:
                        keep.append(d)
                dirnames[:] = keep
    return out


def build_plan(cfg: dict, busy: set[str]) -> dict:
    try:
        hygiene = json.loads((paths.SCRATCH / "git-hygiene.json").read_text(encoding="utf-8"))
    except (OSError, ValueError):
        hygiene = {}
    actions = plan_git(hygiene, cfg) + plan_artifacts(cfg, busy)
    return {"schema_version": 1, "planned_at": now(), "survey_at": hygiene.get("measured_at"),
            "auto_enabled": configuration.enabled("auto_cleanup", "features"),
            "counts": {k: sum(1 for a in actions if a["class"] == k) for k in AUTO_CLASSES + MANUAL_CLASSES},
            "actions": actions}


# --- acting, with a re-check ---------------------------------------------------

def still_safe_branch(a: dict) -> str:
    """"" when the branch may still be deleted under its class, else why not."""
    repo, name, default = a["repo"], a["target"], a["default_branch"]
    if git(repo, "rev-parse", "--verify", "-q", "refs/heads/" + name).returncode:
        return "branch no longer exists"
    held = {l.split(" ", 1)[1].replace("refs/heads/", "") for l in git(repo, "worktree", "list", "--porcelain").stdout.splitlines()
            if l.startswith("branch ")}
    if name in held:
        return "branch is checked out in a worktree now"
    if a["class"] == "branch-merged":
        ahead = git(repo, "rev-list", "--count", f"{default}..{name}").stdout.strip()
        if ahead != "0":
            cherry = git(repo, "cherry", default, name).stdout
            if not cherry or not all(c.startswith("-") for c in cherry.splitlines()):
                return "branch has commits the default branch lacks now"
    if a["class"] == "branch-pushed":
        up = git(repo, "rev-parse", "--abbrev-ref", name + "@{upstream}").stdout.strip()
        if not up or git(repo, "rev-list", "--count", f"{up}..{name}").stdout.strip() != "0":
            return "branch is no longer identical to its upstream"
    return ""


def busy_now(path: str) -> bool:
    from scan_machine import working_dirs
    return any(b == path or b.startswith(path + "/") for b in working_dirs().values())


def act(a: dict, archive: pathlib.Path) -> dict:
    cls, repo, target = a["class"], a.get("repo"), a["target"]
    rec = {"at": now(), "class": cls, "tier": a["tier"], "target": target, **({"repository": a["repository"]} if "repository" in a else {})}
    if cls.startswith("branch-"):
        why = still_safe_branch(a) if cls != "branch-unique" else ""
        if why:
            return {**rec, "result": "skipped", "reason": why}
        sha = git(repo, "rev-parse", "refs/heads/" + target).stdout.strip()
        rec["sha"] = sha
        if cls == "branch-unique":
            archive.mkdir(parents=True, exist_ok=True, mode=0o700)
            bundle = archive / (a["repository"].split(":", 1)[-1].replace("/", "__") + "__" + target.replace("/", "__") + ".bundle")
            made = git(repo, "bundle", "create", str(bundle), "refs/heads/" + target, "^" + a["default_branch"])
            if made.returncode or git(repo, "bundle", "verify", str(bundle)).returncode:
                return {**rec, "result": "failed", "reason": "bundle could not be written and verified; nothing deleted"}
            os.chmod(bundle, 0o600)
            rec["archive"] = str(bundle)
        done = git(repo, "branch", "-D", target)
        return {**rec, "result": "removed" if done.returncode == 0 else "failed",
                **({"reason": done.stderr.strip()[:200]} if done.returncode else {})}
    if cls == "worktree-missing":
        if os.path.exists(target):
            return {**rec, "result": "skipped", "reason": "the directory exists again"}
        git(repo, "worktree", "prune")
        return {**rec, "result": "pruned"}
    if cls in ("worktree-clean", "worktree-dirty"):
        if busy_now(target):
            return {**rec, "result": "skipped", "reason": "a process works inside it now"}
        status = git(target, "status", "--porcelain", "--untracked-files=normal")
        if status.returncode:
            return {**rec, "result": "skipped", "reason": "git status could not be read"}
        if cls == "worktree-clean" and status.stdout.strip():
            return {**rec, "result": "skipped", "reason": "it has uncommitted changes now"}
        rec["head"] = git(target, "rev-parse", "HEAD").stdout.strip()
        if cls == "worktree-dirty":
            dest = archive / (pathlib.Path(target).name + "-" + rec["head"][:8])
            dest.mkdir(parents=True, exist_ok=True, mode=0o700)
            (dest / "tracked.patch").write_text(git(target, "diff", "HEAD", "--binary").stdout)
            (dest / "status.txt").write_text(status.stdout)
            untracked = git(target, "ls-files", "--others", "--exclude-standard", "-z").stdout
            if untracked:
                with tarfile.open(dest / "untracked.tgz", "w:gz") as tar:
                    for name in untracked.split("\0"):
                        if name:
                            tar.add(os.path.join(target, name), arcname=name, recursive=False)
            rec["archive"] = str(dest)
        if not a.get("branch") and rec["head"]:
            # A detached HEAD's commits must stay reachable after the worktree goes.
            git(repo, "branch", f"archive/wt-{rec['head'][:8]}", rec["head"])
        args = ["worktree", "remove", target] + (["--force", "--force"] if cls == "worktree-dirty" else [])
        done = git(repo, *args)
        return {**rec, "result": "removed" if done.returncode == 0 else "failed",
                **({"reason": done.stderr.strip()[:200]} if done.returncode else {})}
    if cls == "build-artifacts":
        if busy_now(target):
            return {**rec, "result": "skipped", "reason": "a process works inside it now"}
        size = subprocess.run(["du", "-sk", target], capture_output=True, text=True).stdout.split()
        shutil.rmtree(target, ignore_errors=True)
        return {**rec, "project": a.get("project"), "kb": int(size[0]) if size else None,
                "result": "removed" if not os.path.exists(target) else "failed"}
    return {**rec, "result": "skipped", "reason": "unknown class"}


def journal(rows: list[dict]) -> None:
    log = paths.STATE / "logs" / "cleanup.jsonl"
    log.parent.mkdir(parents=True, exist_ok=True)
    with open(log, "a", encoding="utf-8") as f:
        for r in rows:
            f.write(json.dumps(r, ensure_ascii=False) + "\n")
    os.chmod(log, 0o600)


def main(argv: list[str]) -> int:
    cfg = load_config()
    from scan_machine import working_dirs
    busy = set(working_dirs().values())
    plan = build_plan(cfg, busy)
    out = paths.SCRATCH / "cleanup-plan.json"
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text(json.dumps(plan, indent=1, ensure_ascii=False), encoding="utf-8")
    os.chmod(out, 0o600)
    counts = ", ".join(f"{k} {v}" for k, v in plan["counts"].items() if v) or "nothing"
    if "--auto" in argv and not plan["auto_enabled"]:
        print(f"cleanup: plan only (features.auto_cleanup is off) — {counts}")
        return 0
    if "--auto" not in argv and "--apply" not in argv:
        print(f"cleanup plan: {counts}. Nothing removed; `--apply` removes the auto tier, "
              f"`--apply --include manual` also archives and removes the manual tier.")
        return 0
    tiers = {"auto"} | ({"manual"} if "--apply" in argv and "manual" in argv else set())
    chosen = [a for a in plan["actions"] if a["tier"] in tiers][: int(cfg.get("max_actions_per_run", 200))]
    archive = configuration.home() / "archive" / "cleanup" / datetime.now(timezone.utc).strftime("%Y-%m-%d")
    rows = []
    for a in chosen:
        try:
            rows.append(act(a, archive))
        except (OSError, subprocess.SubprocessError) as exc:
            rows.append({"at": now(), "class": a["class"], "target": a["target"], "result": "failed",
                         "reason": f"{type(exc).__name__}: {exc}"[:200]})
    journal([{**r, "mode": "auto" if "--auto" in argv else "manual"} for r in rows])
    done = sum(1 for r in rows if r["result"] in ("removed", "pruned"))
    skipped = sum(1 for r in rows if r["result"] == "skipped")
    failed = sum(1 for r in rows if r["result"] == "failed")
    freed = sum(r.get("kb") or 0 for r in rows) / 1048576
    print(f"cleanup: {done} removed, {skipped} skipped on re-check, {failed} failed"
          + (f"; {freed:.1f} GB of build output freed" if freed else ""))
    return 1 if failed else 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
